# Generated by Django 5.1.1 on 2024-11-14 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vendor_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vendorservice'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='vendor_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vendorservice'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot'),
        ),
    ]
